[package]
name    = "modules-optimizer"
version.workspace = true
edition.workspace = true

[dependencies]
core              = { path = "../core" }
egui              = { workspace = true }
egui-phosphor     = { workspace = true }
game              = { path = "../game" }
crossbeam-channel = { workspace = true }
rayon             = "1"
tracing           = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
