[package]
name    = "auto-fishing"
version.workspace = true
edition.workspace = true

[dependencies]
core        = { path = "../core" }
egui        = { workspace = true }
serde       = { workspace = true }
tracing     = { workspace = true }
anyhow      = { workspace = true }

xcap        = "0.0.14"
image       = "0.25"
enigo       = "0.2"
