[package]
name    = "core"
version.workspace = true
edition.workspace = true

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
anyhow      = { workspace = true }
parking_lot = { workspace = true }
indexmap    = { workspace = true }
tracing     = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
egui        = { workspace = true }
dirs-next   = "2"
once_cell   = { workspace = true }
reqwest     = { workspace = true }
