[package]
name    = "encounter-store"
version.workspace = true
edition.workspace = true

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
zstd       = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
tracing    = { workspace = true }
anyhow     = { workspace = true }
dirs-next  = "2"
